package assignment.rssviewer.model;

import java.util.List;
import assignment.rssviewer.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SUGGESTION_CATEGORY.
 */
public class SuggestionCategory {

    private Long id;
    private String name;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SuggestionCategoryDao myDao;

    private List<SuggestionSource> sources;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SuggestionCategory() {
    }

    public SuggestionCategory(Long id) {
        this.id = id;
    }

    public SuggestionCategory(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSuggestionCategoryDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SuggestionSource> getSources() {
        if (sources == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SuggestionSourceDao targetDao = daoSession.getSuggestionSourceDao();
            List<SuggestionSource> sourcesNew = targetDao._querySuggestionCategory_Sources(id);
            synchronized (this) {
                if(sources == null) {
                    sources = sourcesNew;
                }
            }
        }
        return sources;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSources() {
        sources = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
